spring:
  application:
    name: OAuth
  jpa:
      database: MySQL
      show-sql: true
  datasource:
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://192.168.0.17:3306/db_csmdl?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
        username: iot
        password: iot888
        #连接池的配置信息
        initialSize: 10
        minIdle: 10
        maxActive: 100
        maxWait: 60000
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: SELECT 1 FROM DUAL
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxPoolPreparedStatementPerConnectionSize: 20
server:
  port: 8081

